AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-document-process

  Template for serverless-document-process

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 256

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  DocumentTemplateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: edurpa-document-template
    DeletionPolicy: Retain

  FileStorageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: edurpa-file-storage
    DeletionPolicy: Retain

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - POST
          - GET
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"

  UploadSampleDocumentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      ConnectS3:
        Properties:
          Destination:
            Id: DocumentTemplateBucket
          Permissions:
            - Read
            - Write
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /{id}/sample-document
            Method: POST
            ApiId: !Ref MyHttpApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src/upload-sample-document
      DockerTag: python3.9-v1

  GetPresignedUrlSampleDocumentFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectS3:
        Properties:
          Destination:
            Id: DocumentTemplateBucket
          Permissions:
            - Read
    Properties:
      PackageType: Zip
      Handler: src/document-template/app.get_presigned_url_sample_document
      Runtime: python3.9
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: /{id}/sample-document
            Method: GET
            ApiId: !Ref MyHttpApi

  UploadToFileStorageFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectS3:
        Properties:
          Destination:
            Id: FileStorageBucket
          Permissions:
            - Write
    Properties:
      PackageType: Zip
      CodeUri: src/file-storage/
      Handler: app.upload_file
      Runtime: python3.9
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /file-storage
            Method: POST
            ApiId: !Ref MyHttpApi
      Environment:
        Variables:
          JWT_SECRET: 927402
          FILE_STORAGE_BUCKET: edurpa-file-storage

  GetPresignedUrlFileStorageFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectS3:
        Properties:
          Destination:
            Id: FileStorageBucket
          Permissions:
            - Read
    Properties:
      PackageType: Zip
      CodeUri: src/file-storage/
      Handler: app.get_presigned_url
      Runtime: python3.9
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: /file-storage/presigned-url
            Method: GET
            ApiId: !Ref MyHttpApi
      Environment:
        Variables:
          JWT_SECRET: 927402
          FILE_STORAGE_BUCKET: edurpa-file-storage

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UploadSampleDocumentFunction:
    Description: Upload Sample Document Lambda Function ARN
    Value: !GetAtt UploadSampleDocumentFunction.Arn
  GetPresignedUrlSampleDocumentFunction:
    Description: Get Presigned Url Sample Document Lambda Function ARN
    Value: !GetAtt GetPresignedUrlSampleDocumentFunction.Arn
  UploadToFileStorageFunction:
    Description: Upload To File Storage Lambda Function ARN
    Value: !GetAtt UploadToFileStorageFunction.Arn
  GetPresignedUrlFileStorageFunction:
    Description: Get Presigned Url File Storage Lambda Function ARN
    Value: !GetAtt GetPresignedUrlFileStorageFunction.Arn
  MyHttpApi:
    Description: Serverless HTTP API ID
    Value: !Ref MyHttpApi
