AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-document-process

  Template for serverless-document-process

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 256

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  DocumentTemplateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: edurpa-document-template

  ProcessSampleDocumentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      ConnectS3:
        Properties:
          Destination:
            Id: DocumentTemplateBucket
          Permissions:
            - Read
            - Write
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref DocumentTemplateBucket
            Events: s3:ObjectCreated:*
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./process-sample-document
      DockerTag: python3.9-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProcessSampleDocumentFunction:
    Description: Process Sample Document Lambda Function ARN
    Value: !GetAtt ProcessSampleDocumentFunction.Arn
  ProcessSampleDocumentFunctionIamRole:
    Description: Implicit IAM Role created for Process Sample Document function
    Value: !GetAtt ProcessSampleDocumentFunctionRole.Arn
