AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-document-process

  Template for serverless-document-process

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 256

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  DocumentTemplateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: edurpa-document-template
    DeletionPolicy: Retain

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - POST
          - GET
        AllowHeaders:
          - "*"
        AllowOrigins:
          - "*"

  UploadSampleDocumentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Connectors:
      ConnectS3:
        Properties:
          Destination:
            Id: DocumentTemplateBucket
          Permissions:
            - Read
            - Write
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            Path: /{id}/sample-document
            Method: POST
            ApiId: !Ref MyHttpApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./upload-sample-document
      DockerTag: python3.9-v1

  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Connectors:
      ConnectS3:
        Properties:
          Destination:
            Id: DocumentTemplateBucket
          Permissions:
            - Read
    Properties:
      PackageType: Zip
      Handler: get-presigned-url/app.get_presigned_url_handler
      Runtime: python3.9
      Events:
        HttpGet:
          Type: HttpApi
          Properties:
            Path: /{id}/sample-document
            Method: GET
            ApiId: !Ref MyHttpApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UploadSampleDocumentFunction:
    Description: Upload Sample Document Lambda Function ARN
    Value: !GetAtt UploadSampleDocumentFunction.Arn
  UploadSampleDocumentFunctionIamRole:
    Description: Implicit IAM Role created for Upload Sample Document function
    Value: !GetAtt UploadSampleDocumentFunctionRole.Arn
  GetPresignedUrlFunction:
    Description: Get Presigned Url Lambda Function ARN
    Value: !GetAtt GetPresignedUrlFunction.Arn
  GetPresignedUrlFunctionIamRole:
    Description: Implicit IAM Role created for Get Presigned Url function
    Value: !GetAtt GetPresignedUrlFunctionRole.Arn
  MyHttpApi:
    Description: Serverless HTTP API ID
    Value: !Ref MyHttpApi
